# Generated by Django 3.2.6 on 2023-08-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0005_auto_20230828_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='MilitaryOrganization',
        ),
        migrations.RenameModel(
            old_name='UnitPowerType',
            new_name='MilitaryOrganizationPowerType',
        ),
        migrations.AlterModelOptions(
            name='militaryorganization',
            options={'verbose_name': 'MilitaryOrganization', 'verbose_name_plural': 'MilitaryOrganization'},
        ),
        migrations.AlterModelOptions(
            name='militaryorganizationpowertype',
            options={'verbose_name': 'MilitaryOrganizationPowerType', 'verbose_name_plural': 'MilitaryOrganizationPowerTypes'},
        ),
        migrations.AlterModelTable(
            name='militaryorganization',
            table='MilitaryOrganization',
        ),
        migrations.AlterModelTable(
            name='militaryorganizationpowertype',
            table='MilitaryOrganizationPowerType',
        ),
    ]
