# Generated by Django 3.2.6 on 2023-08-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0007_vehiclepowertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guarani',
            new_name='Vehicle',
        ),
    ]
