# Generated by Django 3.2.6 on 2023-09-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0010_vehicle_vehicle_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='category',
        ),
    ]
