# Generated by Django 3.2.6 on 2023-06-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('VisibilityRange', models.FloatField(blank=True, max_length=30, null=True)),
                ('v_min', models.FloatField(blank=True, max_length=30, null=True)),
                ('v_max', models.FloatField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryOrganization',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryorganization')),
            ],
            options={
                'verbose_name': 'MilitaryOrganization',
                'verbose_name_plural': 'MilitaryOrganization',
                'db_table': 'MilitaryOrganization',
            },
        ),
        migrations.CreateModel(
            name='MilitaryScenario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MilitaryScenario',
                'verbose_name_plural': 'MilitaryScenario',
                'db_table': 'MilitaryScenario',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='militaryScenarioConf.carrier')),
                ('category', models.CharField(choices=[('armored', 'Armored')], default='armored', max_length=30)),
            ],
            bases=('militaryScenarioConf.carrier',),
        ),
        migrations.CreateModel(
            name='MilitaryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=30)),
                ('CommDevice_Carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commdevicecarrier', to='militaryScenarioConf.carrier')),
                ('Military_Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryorganization')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryscenario')),
            ],
            options={
                'verbose_name': 'MilitaryPerson',
                'verbose_name_plural': 'MilitaryPerson',
                'db_table': 'MilitaryPerson',
            },
        ),
        migrations.CreateModel(
            name='MilitaryOrganizationPowerType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryorganizationpowertype')),
            ],
            options={
                'verbose_name': 'MilitaryOrganizationPowerType',
                'verbose_name_plural': 'MilitaryOrganizationPowerTypes',
                'db_table': 'MilitaryOrganizationPowerType',
            },
        ),
        migrations.AddField(
            model_name='militaryorganization',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryscenario'),
        ),
        migrations.AddField(
            model_name='militaryorganization',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryorganizationpowertype'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryscenario'),
        ),
        migrations.CreateModel(
            name='Guarani',
            fields=[
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='militaryScenarioConf.platform')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('militaryScenarioConf.platform',),
        ),
        migrations.AddField(
            model_name='platform',
            name='Military_Organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryorganization'),
        ),
    ]
