# Generated by Django 3.2.6 on 2023-07-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0002_maytalkto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MayTalkTo',
        ),
    ]
