# Generated by Django 3.2.6 on 2023-08-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0003_delete_maytalkto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MilitaryOrganization',
            new_name='Unit',
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Unit'},
        ),
        migrations.AlterModelTable(
            name='unit',
            table='Unit',
        ),
    ]
