# Generated by Django 3.2.6 on 2023-09-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0009_vehicle_vehiclepowertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_specialization',
            field=models.CharField(choices=[('armored', 'Armored')], default='armored', max_length=30),
        ),
    ]
