# Generated by Django 3.2.6 on 2023-06-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='stop_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
