# Generated by Django 3.2.6 on 2023-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_configuration_stop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
