# Generated by Django 3.2.6 on 2023-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20230606_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='antenna_gain',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='range',
        ),
        migrations.RemoveField(
            model_name='station',
            name='antenna_gain',
        ),
        migrations.RemoveField(
            model_name='station',
            name='range',
        ),
        migrations.AddField(
            model_name='interface',
            name='antenna_gain_intf0',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='antenna_gain_intf1',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='range_intf0',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='range_intf1',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
