# Generated by Django 3.2.6 on 2023-07-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_maytalkto_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maytalkto',
            old_name='listener',
            new_name='interf_1',
        ),
        migrations.RenameField(
            model_name='maytalkto',
            old_name='speaker',
            new_name='interf_2',
        ),
    ]
