# Generated by Django 3.2.6 on 2023-07-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_auto_20230718_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maytalkto',
            old_name='interf_1',
            new_name='talker_1',
        ),
        migrations.RenameField(
            model_name='maytalkto',
            old_name='interf_2',
            new_name='talker_2',
        ),
    ]
