# Generated by Django 3.2.6 on 2023-08-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0003_delete_maytalkto'),
        ('configurator', '0008_auto_20230718_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='militaryperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryperson'),
        ),
    ]
