# Generated by Django 3.2.6 on 2023-09-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_delete_interfacepowertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
