# Generated by Django 3.2.6 on 2023-07-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0003_delete_maytalkto'),
        ('configurator', '0004_auto_20230701_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='MayTalkTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=30)),
                ('speaker', models.CharField(max_length=30)),
                ('listener', models.CharField(max_length=30)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryscenario')),
            ],
            options={
                'verbose_name': 'MayTalkTo',
                'verbose_name_plural': 'MayTalkTo',
                'db_table': 'MayTalkTo',
            },
        ),
    ]
