# Generated by Django 3.2.6 on 2023-07-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_maytalkto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maytalkto',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.network'),
        ),
    ]
