# Generated by Django 3.2.6 on 2023-09-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_alter_node_militaryperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterfacePowerType',
        ),
    ]
